### ISSUE TITLE
Spanish translation.

### ISSUE THREAD

**Issue by vidimus** [Diesdooi/CenarioOMalQueNuncaDorme#1]
Hello, @Diesdooi 

I've finished the Spanish translation. Now I have to test it and review after that. I will send you a message as soon as I have it ready.

**Comment by vidimus** [comment]
Hello, @Diesdooi 
My idea is to send you the translation by the end od this week.

**Comment by Diesdooi** [comment]
Hello, Vidimus
It’s good News!

Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: ***@***.***>
Enviado:segunda-feira, 15 de março de 2021 12:19
Para: ***@***.***>
***@***.***>; ***@***.***>
Assunto: Re: [Diesdooi/CenarioOMalQueNuncaDorme] Spanish translation. (#1)


Hello, @Diesdooi<https://github.com/Diesdooi>
My idea is to send you the translation by the end od this week.

**Comment by vidimus** [comment]
Hello, @Diesdooi 

Here's the file with the Spanish translation:

[Localization.Spanish.txt](https://github.com/Diesdooi/CenarioOMalQueNuncaDorme/files/6160322/Localization.Spanish.txt)

Foi um prazer jogar e traduzir o cenário. Só resta aguardar que os jogadores espanhóis gostem tanto do cenário como eu gostei.

**Comment by vidimus** [comment]
@Diesdooi Olà, tudo bem com o arquivo? Eu posso fazer o pacote se resultar mais cómodo para voçê.

**Comment by Diesdooi** [comment]
Hello, @Vidimus

Yes, it would be great. And send me the file of the latest version Dracula, please. I will upload both.

Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: ***@***.***>
Enviado:sábado, 20 de março de 2021 04:55
Para: ***@***.***>
***@***.***>; ***@***.***>
Assunto: Re: [Diesdooi/CenarioOMalQueNuncaDorme] Spanish translation. (#1)


@Diesdooi<https://github.com/Diesdooi> Olà, tudo bem com o arquivo? Eu posso fazer o pacote se resultar mais cómodo para voçê.

**Comment by vidimus** [comment]
O mal que nunca dorme:

O pacote está neste repositório. Eu tive de dividir em dois (é muito grande para a minha conta de github)

https://github.com/vidimus/Valkyrie-Mom-scenarios-translations/tree/master/El%20mal%20que%20nunca%20duerme

Sâo os dos arquivos "OMalqueNuncaDorme .zip.001 e OMalqueNuncaDorme .zip.002"

**Comment by vidimus** [comment]
Do cenário "Drácula" a última versâo é do mes passado:

[Drácula.zip](https://github.com/Diesdooi/CenarioOMalQueNuncaDorme/files/6176507/Dracula.zip)

**Comment by vidimus** [comment]
@Diesdooi  faltou carregar o ficheiro .ini para fazer corretamente a actualização (além do .valkyrie)

**Comment by Diesdooi** [comment]
Sim. Por favor me envie o arquivo .ini porque encontrei apenas o .Valkyrie em sua pasta.

Obter o Outlook para Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by vidimus** [comment]
@Diesdooi O ficheiro .ini:

[OMalqueNuncaDorme.zip](https://github.com/Diesdooi/CenarioOMalQueNuncaDorme/files/6178496/OMalqueNuncaDorme.zip)

**Comment by vidimus** [comment]
Há um usuário do Discord que está a fazer a traduçâo do cenário "Dracula" en inglês (eu estou a ajudar-lhe com a parte técnica, crear o ficheiro e dar umas dicas).

**Comment by Diesdooi** [comment]
Obrigado! Ok, manteremos contato. Estou terminando de criar meu terceiro cenário, devo postá-lo essa semana.

Obter o Outlook para Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by vidimus** [comment]
> Obrigado! Ok, manteremos contato. Estou terminando de criar meu terceiro cenário, devo postá-lo essa semana. Obter o Outlook para Android<https://aka.ms/AAb9ysg>
> 
"O mal que nunca dorme" já está em espanhol. Obrigado.

Bõa notícia! De seguro que o vou jogar!

O tradutor inglês do Dracula está à espera duma resposta para continúar a tradução. Posso dizer-lhe de continúar?

**Comment by Diesdooi** [comment]
Pode sim!

Obter o Outlook para Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by vidimus** [comment]
Olá, @Diesdooi 

A traduçâo inglêsa está quase pronta. O usuário enviou-me uma lista de erros que ele encontrou a jogar o cenário:

> Search tokens not being removed after all options were exhausted. The skeleton in the gallery has something in each hand but the token always remains. Once you discover the tools under the floorboards the token remains so you go back and do the puzzle again, which spawns the monsters again. Also, the creature in the lake. If you don’t feed it it comes into the castle after you and if you defeat it then it just states that it slides back into the lake - which is impossible when you are in the castle

> Also, when you enter the library, there is no prompt to place a door at the spot where you are entering the room as it is a solid wall where you enter the library

**Comment by vidimus** [comment]
Olá, @Diesdooi 
Há uma nova actualizaçâo da traduçâo espanhola, com voz para as narraçôes do prólogo e dos epílogos.

Os ficheiros estâo aquim (eu fiz já o pacote adicionando o audio em espanhol), neste repositório. Eu tive de dividir em cinco (é muito grande para a minha conta de github)

https://github.com/vidimus/Valkyrie-Mom-scenarios-translations/tree/master/El%20mal%20que%20nunca%20duerme

Sâo os arquivos  desdes "OMalqueNuncaDorme .zip.001 até OMalqueNuncaDorme .zip.005"

**Comment by vidimus** [comment]
@Diesdooi Se tiver algum problema com o pacote novo, é só avisar-me

**Comment by vidimus** [comment]
o cenário ainda não está actualizado, nem este nem o do mal que nunca dorme

**Comment by Diesdooi** [comment]
Eu coloquei o arquivo mais recente na pasta, então a narração em espanhol funcionou. Há alguma versão ainda mais recente?

Obter o Outlook para Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by vidimus** [comment]
Sim , esta é a última:

https://drive.google.com/file/d/1FHCF6aMnJKaUvQ4DwljDCmIicMLucSU6/view?usp=sharing

**Comment by vidimus** [comment]
E do cenário "Drácula" também há uma nova:

https://drive.google.com/file/d/1iW8EqtdcwSHnNy_zX0TdBz7sIaYoGr-X/view?usp=sharing

Têm a narração em espanhol e a traduzão/narração em inglês

**Comment by Diesdooi** [comment]
Ok. Ainda hoje vou fazer o upload dos arquivos.

Obter o Outlook para Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by vidimus** [comment]
@Diesdooi  I've changed the Dracula's scenario file. It looks there's a problem creating the packages with the new Valkyrie version. 

I've downgrade the program and it works fine. Maybe you have the same problem with the Claustrofobia scenario.

Here's the open issue, if you want to have a look.
https://github.com/NPBruce/valkyrie/issues/1485

**Comment by Diesdooi** [comment]
Eu notei que há um problema, talvez com essas novas versões do Valkyrie. Quando coloquei “espanhol” nas configurações, os textos de “Claustrofobia” saíram em branco. Mas quando coloquei “Português”, ele funcionou normalmente. Experimente mudar o idioma nas configurações e teste novamente o “Claustrofobia”.

Em meu dispositivo o Valkyrie apenas carrega os cenários se estiver em sua versão mais recente. Imagino que se eu fizer o downgrade, não funcionará. Eu vou acompanhar essa issue e ver a solução.

Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: ***@***.***>
Enviado:domingo, 11 de abril de 2021 16:23
Para: ***@***.***>
***@***.***>; ***@***.***>
Assunto: Re: [Diesdooi/CenarioOMalQueNuncaDorme] Spanish translation. (#1)


@Diesdooi<https://github.com/Diesdooi> I've changed the Dracula's scenario file. It looks there's a problem creating the packages with the new Valkyrie version.

I've downgrade the program and it works fine. Maybe you have the same problem with the Claustrofobia scenario.

Here's the open issue, if you want to have a look.
NPBruce/valkyrie#1485<https://github.com/NPBruce/valkyrie/issues/1485>

**Comment by vidimus** [comment]
> Eu notei que há um problema, talvez com essas novas versões do Valkyrie. Quando coloquei “espanhol” nas configurações, os textos de “Claustrofobia” saíram em branco. Mas quando coloquei “Português”, ele funcionou normalmente. Experimente mudar o idioma nas configurações e teste novamente o “Claustrofobia”. Em meu dispositivo o Valkyrie apenas carrega os cenários se estiver em sua versão mais recente. Imagino que se eu fizer o downgrade, não funcionará. Eu vou acompanhar essa issue e ver a solução.

É certo, não mostra os cenários da versão anterior. Muito exquisito... Só resta aguardar a solução

**Comment by vidimus** [comment]
O Valkyrie agora faz bem o ficheiro. O novo pacote esta neste link:

https://github.com/vidimus/Valkyrie-Mom-scenarios-translations/tree/master/OMalqueNuncaDorme

**Comment by vidimus** [comment]
Você tem uma conta em Discord? Talvez fosse mais fácil e rápido enviar os arquivos e receber avisos

**Comment by vidimus** [comment]
@Diesdooi ?
